const items=[["绳上花开","Knots in Bloom","selected/knots-in-bloom.jpg","portfolio.html#knots-in-bloom"],["读书文化节","Reading Culture Festival","posters/reading-opening-new.jpg","portfolio.html#reading-festival"],["原创班牌绘画","Original Class Sign Illustration","illustrations/class-sign.jpg","portfolio.html#class-sign"],["国际化的北京","International Beijing","selected/international-beijing.jpg","portfolio.html#international-beijing"],["学生组织招新","Student Organization Recruitment","posters/recruitment-1.jpg","portfolio.html#recruitment-posters"],["请柬设计","Invitation Design","materials/invitation-layout.png","portfolio.html#invitation-design"],["养元青广告","Glow, Not Grease","selected/glow-not-grease.jpg","portfolio.html#glow-not-grease"],["周边物料与宣传图","Merchandise and Promotional Graphics","materials/merchandise-promotion.png","portfolio.html#merchandise-design"],["大王扇设计","Oversized Hand Fan Design","materials/oversized-hand-fan.jpg","portfolio.html#hand-fan-design"],["墨规万物","Mozi’s Rules","selected/mozis-rules.jpg","portfolio.html#mozis-rules"],["倒带","Rewind","selected/rewind.jpg","portfolio.html#rewind"],["胡凯：忠于自己，活在当下","Hu Kai: Be True to Yourself, Live in the Present","articles/hu-kai/page-2.png","article-hu-kai.html"],["文耀青春，共赴新程","Shine for Culture & Communication, Embark on a New Journey Together","articles/recruitment/page-2.png","article-recruitment.html"],["传承文化之美，共赴春日之约","Celebrating Cultural Beauty, Meeting in Spring","articles/spring/page-2.png","article-spring.html"]];
const urls=items.map(item=>item[2]);
const grid=document.querySelector('#projects');
items.forEach((item,i)=>{const figure=document.createElement('figure');figure.className='project';const link=document.createElement('a');link.href=item[3];const img=new Image();img.src=item[2];img.alt=item[0]+'｜'+item[1];img.loading=i<3?'eager':'lazy';if(item[2].startsWith('articles/'))img.className='article-representative';const caption=document.createElement('figcaption');const title=document.createElement('span');title.textContent=item[0];const sub=document.createElement('small');sub.textContent=item[1];title.append(sub);const number=document.createElement('span');number.className='project-number';number.textContent=String(i+1).padStart(2,'0');caption.append(title,number);link.append(img,caption);figure.append(link);grid.append(figure)});
const trailUrls=Array.from({length:7},(_,i)=>'trail/skill-'+(i+1)+'.png');
trailUrls.forEach(src=>{const preload=new Image();preload.src=src;});
const hero=document.querySelector('.hero'),trail=document.querySelector('.trail');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let previous=null,counter=0,lastTime=0;
function spawn(x,y){if(reduced.matches)return;const img=new Image();img.src=trailUrls[counter++%trailUrls.length];img.alt='';img.style.left=x+'px';img.style.top=y+'px';trail.append(img);const tilt=(counter%5-2)*5;const animation=img.animate([{opacity:0,transform:`translate(-50%,-40%) rotate(${tilt}deg) scale(.85)`},{opacity:1,transform:`translate(-50%,-50%) rotate(${tilt}deg) scale(1)`,offset:.16},{opacity:1,transform:`translate(-50%,-55%) rotate(${tilt}deg) scale(1)`,offset:.5},{opacity:0,transform:`translate(-50%,-68%) rotate(${tilt}deg) scale(.94)`}],{duration:1350,easing:'ease-out'});animation.onfinish=()=>img.remove();while(trail.children.length>12)trail.firstChild.remove()}
hero.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=hero.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const now=performance.now();if((!previous||Math.hypot(x-previous.x,y-previous.y)>72)&&now-lastTime>90){spawn(x,y);previous={x,y};lastTime=now}});
hero.addEventListener('pointerleave',()=>previous=null);
hero.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){const rect=hero.getBoundingClientRect();spawn(e.clientX-rect.left,e.clientY-rect.top)}});
